### PR TITLE
Monkey patches certifi.where() to load OS mounted CA path (KO-2744) a…

### PR DESCRIPTION
**Pull request by mikeatlas-r7**
…lso see PR https://github.com/komand/plugin-sdk-python/pull/57

### CODE REVIEW

**Comment by mikeatlas-r7** [comment]
@mrinehart-r7 I don't really understand how the test in drone is failing - doesn't seem related to my changes. If they are related to my changes, though, can you help me get started on what to fix?

(cc @mbroomfield-r7 @jonschipp )

**Comment by mrinehart-r7** [comment]
@mikeatlas-r7 

`ImportError: No module named certifi`

**Comment by mikeatlas-r7** [comment]
Explicitly added certifi,  think the tests

**Comment by mikeatlas-r7** [comment]
now le build passes

**Comment by mbroomfield-r7** [comment]
This has already been merged. I think this should be closed, as I already handled the certify fix on the master branch

**Comment by mrinehart-r7** [comment]
Good to go @mikeatlas-r7

**Pull request merged**
