### PR TITLE
Make sure python plugin test errors return the correct exit code

### PR DESCRIPTION
**Pull request by jcsalem**
Fixes KO-916: Plug in test errors in Python didn't force an exit code != 0

I tested this by hand by throwing an exception from the test function. Prior to this patch, the test passed (even though it had status: "error" after this patch, the test failed.

### CODE REVIEW

**Comment by jandre** [comment]
OK w/ merging once tests are fixed, but wonder why this isn't getting caught, anything test returns False should `exit(1)`: https://github.com/komand/plugin-sdk-python/blob/master/komand/plugin.py#L63-L64

Super weirddd

**Comment by jcsalem** [comment]
I bet this is happening because I have an old komand/plugin-python:0.1.0 image that everything is built from.  And image was built 10 weeks ago!
I'm trying to test this theory but I can't delete that image because there are children build from it.  Grrr... Super hard to delete just those children.

**Comment by jcsalem** [comment]
Ya, I think the komand/python-plugin:0.1.0 and 0.2.0  images need to be rebuilt from master.
I don't know how to do that.

**Comment by jandre** [comment]
You can do `docker pull komand/python-plugin:0.2` and then rebuild your containers that are using them, Jim.  

Locally,  if you want to tag a version, I'd suggest doing `docker tag komand/python-plugin komand/python-plugin:0.2`

**Comment by jcsalem** [comment]
I did a new docker pull but still had the same result.

**Comment by jandre** [comment]
Ah, I think one of the problems is we are not updating the version in setup.py, which makes it hard to identify what SDK is being used.  I'll add this and some dev/release process documentation

**Comment by jonschipp** [comment]
Instead of having to do `docker pull komand/python-plugin:0.2` before building our plugin images to ensure we have latest SDK, we can add the `--pull` argument to `docker build` in the plugin Makefiles. I create a PR for it.

**Comment by jandre** [comment]
Closing this because I *believe* this was already resolved once the tagged upstream builds were fixed.  Will re-open if we notice this issue again.

**Pull request closed without merging**
