### PR TITLE
Updated to support Python 3.6.4 and pip 9.0.1

### PR DESCRIPTION
**Pull request by Rickerd0613**
Taken from others doing similar things:
* https://github.com/docker-library/python/blob/master/3.6/jessie/slim/Dockerfile
* https://github.com/docker-library/python/blob/master/3.6/alpine3.4/Dockerfile
* https://hub.docker.com/r/micalexander/alpine-python-3.6.1/~/dockerfile/

### CODE REVIEW

**Comment by mbroomfield-r7** [comment]
@Rickerd0613 The CI build is failing, and I believe this is because a library we use, python-jsonschema-objects, might not be Python 3.6 compatible.

https://ci.dev.komand.net/komand/plugin-sdk-python/426
^ If you can see that

```
Searching for jsonschema==2.3.0
Best match: jsonschema 2.3.0
Processing jsonschema-2.3.0-py3.6.egg

Using /usr/local/lib/python3.6/site-packages/jsonschema-2.3.0-py3.6.egg
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    test_suite="tests.komand_test_suite",
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 198, in run
    installed_dists = self.install_dists(self.distribution)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 193, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires or [])
  File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1115, in best_match
    dist = working_set.find(req)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 719, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (python-jsonschema-objects 0.3.0+34.gd19f864 (/usr/local/lib/python3.6/site-packages), Requirement.parse('python_jsonschema_objects==0.3.1'))
make: *** [test] Error 1
Makefile:19: recipe for target 'test' failed
[info] build failed (exit code 2)
```

https://github.com/cwacek/python-jsonschema-objects/blob/master/setup.py#L90

Can you confirm that the commands `make all` and `make test` execute without any errors?
I'm pretty sure we'll need to work to make python-jsonschema-objects Python 3.6 compatible.

**Comment by Rickerd0613** [comment]
@mbroomfield-r7 When I build the docker container with Python 3.6 and ran the tests in side it, I did not have those errors.
screen shot 2018-02-13 at 10 04 42 am
Even manually installing that version of python-jsonschema-objects worked (it appears as though one is already installed).
screen shot 2018-02-13 at 10 12 25 am
I'm I not running the same tests you are or could I be working with a different environment?

**Comment by Rickerd0613** [comment]
@mbroomfield-r7 Not sure if the CI is not happy with the way I committed the changes but if you checkout this branch, build it, and run `make all` inside the container everything seems to work. Let me know if there is still an issue. 

Thanks again for helping with this.

**Comment by mikeatlas-r7** [comment]
bump 
...and thanks for the PR @Rickerd0613 !

**Comment by Rickerd0613** [comment]
@mbroomfield-r7 could you guys add this to your docker hub under a new tag? That would make it the easiest for me to test one of our custom plugins using Komand. It doesn't have to be latest, any tag I can reference will work.

**Comment by mbroomfield-r7** [comment]
@Rickerd0613 No worries, I just tested real quick and it worked fine.

This PR should be good to go

**Comment by Rickerd0613** [comment]
@mrinehart-r7 Incremented the version number. Should be good to go.

**Comment by mrinehart-r7** [comment]
LGTM, thank you @Rickerd0613 ! Appreciate your work on this. Merging!

**Pull request merged**
