### PR TITLE
Feature/swarm support cleanup

### PR DESCRIPTION
**Pull request by StabbyCutyou**
ping @rossnanop @jandre

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
WIP don't merge yet, but provide feedback as though you want to.

**Comment by StabbyCutyou** [comment]
pls review

**Comment by StabbyCutyou** [comment]
please look at meeeeeeeee

**Comment by rossnanop** [comment]
@StabbyCutyou Code looks good if you've tested it.

**Comment by StabbyCutyou** [comment]
I have, but this is just going to into the main PR so it's not end of the world if there are bugs.

**Pull request merged**
